### ISSUE TITLE
Thank you for your work. I also used your project to make my website.

### ISSUE THREAD

**Issue by huguadao** [tailwindtoolbox/Landing-Page#34]
I Hope To Add My Project Address https://qiusheji.com  To Readme.md 😄（The Chinese name is 求设计, and the advantage is that it needs to be designed.）

After going online, I found that it still takes some time to load this file tailwind.min.css. I don't know if there are any alternative public images.

**Comment by tailwindtoolbox** [comment]
hey, happy to add it - love the colour choice.

You can save [the css file](https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css) and store it locally with your html file instead of using the cdn version.

This is the old version of tailwind and has all the classes - so ideally you will want to run it through purgecss (can do this online using this: https://purifycss.online/) and then save the css file.

I've done this for you (assuming you're not planning on changing anything else now)

Copy this file to the same folder as your html file, rename it to styles.pure.css and add this to the html:

`<link rel="stylesheet" href="styles.pure.css"/>`

Remove these lines:
```
<link rel="stylesheet" href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css"/>
<!-- <link rel="stylesheet" href="./assets/tailwind.min.css"/> -->
<!--Replace with your tailwind.css once created-->
<link href="https://fonts.loli.net/css?family=Source+Sans+Pro:400,700" rel="stylesheet" />
```

[styles.pure.txt](https://github.com/tailwindtoolbox/Landing-Page/files/10185230/styles.pure.txt)
